- hosts: web
  tasks:
    - name: Load image
      command: docker load -i /tmp/mynginx.tar

    - name: Stop old container
      command: docker stop myapp
      ignore_errors: yes

    - name: Remove old container
      command: docker rm myapp
      ignore_errors: yes

    - name: Run container
      command: docker run -d -p 80:80 --name myapp mynginx
