name: deploy-custom-nginx

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t mynginx .

      - name: Save image
        run: docker save mynginx | gzip > mynginx.tar.gz

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.60.33.63 >> ~/.ssh/known_hosts

      - name: Copy image to server
        run: scp mynginx.tar.gz ec2-user@13.60.33.63:/tmp/

      - name: Load and run container
        run: |
          ssh ec2-user@13.60.33.63 << 'EOF'
            docker load < /tmp/mynginx.tar.gz
            docker stop myapp || true
            docker rm myapp || true
            docker run -d -p 80:80 --name myapp mynginx
          EOF
