name: deploy-custom-nginx

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Setup SSH
      run: |
       mkdir -p ~/.ssh
       echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
       chmod 600 ~/.ssh/id_rsa

    - name: Test SSH
      run: |
       ssh -o StrictHostKeyChecking=no ec2-user@13.60.33.63 "echo CONNECTED"
    
